In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [6]:
import time 

a= np.random.rand(1000000)
b= np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc=time.time()

print("The Vectorized version : %s \nComputation time : %s ms\n " % (c,str(1000*(toc-tic))))

c = 0
tic - time.time()
for i in range(100000):
    c+= a[i]*b[i]
toc=time.time()
    
print("The Vectorized version : %s \nComputation time : %s ms " % (c,str(1000*(toc-tic))))    


The Vectorized version : 249820.34180174195 
Computation time : 1.0013580322265625 ms
 
The Vectorized version : 24887.80457556378 
Computation time : 60.83559989929199 ms 


In [7]:
a,b

(array([0.03296535, 0.47724845, 0.29772534, ..., 0.33893182, 0.77548171,
        0.94583812]),
 array([0.93097286, 0.68879842, 0.00691976, ..., 0.79137064, 0.09556402,
        0.19373479]))

In [8]:
a[i]

0.44813603976045346

In [9]:
a[0]

0.03296535189232819

In [20]:
a = np.random.rand(10)
b = np.random.rand(10)

t = time.time()
x = np.dot(a,b)
s = time.time()

print("The Vectorized version : %s \nComputation time : %s ms " % (x,str(1000*(s-t)))) 



The Vectorized version : 1.4669955826913676 
Computation time : 9.006977081298828 ms 


In [25]:
v = np.random.rand(100,1)

In [26]:
v

array([[0.23436327],
       [0.36129185],
       [0.19322777],
       [0.0101846 ],
       [0.43072429],
       [0.54760038],
       [0.60278398],
       [0.42320629],
       [0.33765549],
       [0.02587156],
       [0.78503061],
       [0.63620389],
       [0.40514545],
       [0.18902046],
       [0.12868764],
       [0.64578658],
       [0.32260196],
       [0.42857529],
       [0.38608143],
       [0.60944958],
       [0.80188717],
       [0.47557406],
       [0.25723925],
       [0.04272089],
       [0.21845612],
       [0.91678294],
       [0.1000401 ],
       [0.15543186],
       [0.76576558],
       [0.51980122],
       [0.48587497],
       [0.21499068],
       [0.37988336],
       [0.23781146],
       [0.357087  ],
       [0.87494051],
       [0.71757734],
       [0.5136545 ],
       [0.86134531],
       [0.11688257],
       [0.03053354],
       [0.18123165],
       [0.11939279],
       [0.2539653 ],
       [0.8139148 ],
       [0.05007635],
       [0.33971483],
       [0.955

In [27]:
y = np.exp(v)

In [28]:
y

array([[1.26410362],
       [1.43518225],
       [1.21315908],
       [1.01023664],
       [1.53837134],
       [1.72909885],
       [1.82719861],
       [1.52684924],
       [1.40165753],
       [1.02620913],
       [2.19247406],
       [1.88929527],
       [1.49952059],
       [1.20806567],
       [1.13733481],
       [1.90748683],
       [1.38071566],
       [1.53506894],
       [1.47120446],
       [1.83941867],
       [2.22974488],
       [1.60893755],
       [1.29335453],
       [1.04364656],
       [1.24415442],
       [2.50123082],
       [1.10521523],
       [1.16816234],
       [2.15064023],
       [1.68169333],
       [1.62559673],
       [1.23985034],
       [1.46211404],
       [1.26847001],
       [1.4291602 ],
       [2.39873258],
       [2.04946204],
       [1.67138813],
       [2.36634203],
       [1.12398743],
       [1.03100447],
       [1.19869282],
       [1.12681243],
       [1.28912708],
       [2.25672534],
       [1.05135137],
       [1.404547  ],
       [2.599

In [30]:
np.log(y)

array([[0.23436327],
       [0.36129185],
       [0.19322777],
       [0.0101846 ],
       [0.43072429],
       [0.54760038],
       [0.60278398],
       [0.42320629],
       [0.33765549],
       [0.02587156],
       [0.78503061],
       [0.63620389],
       [0.40514545],
       [0.18902046],
       [0.12868764],
       [0.64578658],
       [0.32260196],
       [0.42857529],
       [0.38608143],
       [0.60944958],
       [0.80188717],
       [0.47557406],
       [0.25723925],
       [0.04272089],
       [0.21845612],
       [0.91678294],
       [0.1000401 ],
       [0.15543186],
       [0.76576558],
       [0.51980122],
       [0.48587497],
       [0.21499068],
       [0.37988336],
       [0.23781146],
       [0.357087  ],
       [0.87494051],
       [0.71757734],
       [0.5136545 ],
       [0.86134531],
       [0.11688257],
       [0.03053354],
       [0.18123165],
       [0.11939279],
       [0.2539653 ],
       [0.8139148 ],
       [0.05007635],
       [0.33971483],
       [0.955

In [201]:
w = np.random.rand(1,6)
print(w)
x = np.random.randint(low=1,high=6,size=(6,1))
x

[[0.39876209 0.70562152 0.24146902 0.84020046 0.16489982 0.23732347]]


array([[3],
       [3],
       [4],
       [4],
       [4],
       [5]])

In [202]:
len(x)

6

In [203]:
b = [1]

In [204]:
z = np.zeros(2)
z[1]

0.0

In [205]:
np.append(z,b)

array([0., 0., 1.])

In [206]:
#for loop
z = np.zeros(1)
for i in range(6):
    z+= w[0][i]*x[i]
    
z+=b
   
    
print(z)



[10.48604535]


In [186]:
w[0][0]*x[0]

array([2.54203082])

In [207]:
#Vectorization
z = np.dot(w,x) + b

In [208]:
z

array([[10.48604535]])